import { SceneBlueprint } from "../types/types";

export const SceneBlueprints: Record<string, SceneBlueprint> = {
  fsc_signature: {
    id: "fsc_signature",
    version: "3.0.0",
    name: "FSC Signature Studio (Lilongwe Flagship)",
    brandId: "BRAND_FSC_001",
    environmentId: "ENV_FLAGSHIP_ARCH_001",
    compositionId: "COMP_HERO_PORTRAIT_001",
    defaultStylePackId: "STYLE_LUXURY_EDITORIAL_001",
    defaultBrandingId: "BRAND_MOUNTED_3D_001",
    allowedVariantIds: ["VAR_MORNING_001", "VAR_EVENING_002", "VAR_LUXURY_LAUNCH_003"],
    mandatoryShotIds: ["SHOT_HERO_001", "SHOT_LOOKBOOK_002"],
    createdBy: "Nuerex Enterprise System",
    approvedBy: "Chief Creative Officer",
    approvalDate: "2026-08-01",
    usageCount: 1420,
    performanceScore: 97.4,
    deprecated: false
  },
  luxury_white: {
    id: "luxury_white",
    version: "3.0.0",
    name: "FSC Luxury White Studio",
    brandId: "BRAND_FSC_001",
    environmentId: "ENV_LUXURY_WHITE_002",
    compositionId: "COMP_PRODUCT_HERO_002",
    defaultStylePackId: "STYLE_APPLE_MINIMAL_002",
    defaultBrandingId: "BRAND_MOUNTED_3D_001",
    allowedVariantIds: ["VAR_MINIMAL_004", "VAR_EDITORIAL_005"],
    mandatoryShotIds: ["SHOT_HERO_001", "SHOT_SIDE_003"],
    createdBy: "Nuerex Enterprise System",
    approvedBy: "Chief Creative Officer",
    approvalDate: "2026-08-01",
    usageCount: 980,
    performanceScore: 94.8,
    deprecated: false
  },
  lifestyle_home: {
    id: "lifestyle_home",
    version: "3.0.0",
    name: "FSC Lifestyle Residence",
    brandId: "BRAND_FSC_001",
    environmentId: "ENV_LIFESTYLE_RESIDENCE_003",
    compositionId: "COMP_EDITORIAL_003",
    defaultStylePackId: "STYLE_LUXURY_EDITORIAL_001",
    defaultBrandingId: "BRAND_BRASS_PLAQUE_002",
    allowedVariantIds: ["VAR_MORNING_001", "VAR_EDITORIAL_005"],
    mandatoryShotIds: ["SHOT_LOOKBOOK_002", "SHOT_HERO_001"],
    createdBy: "Nuerex Enterprise System",
    approvedBy: "Chief Creative Officer",
    approvalDate: "2026-08-01",
    usageCount: 750,
    performanceScore: 93.2,
    deprecated: false
  },
  outdoor_fashion: {
    id: "outdoor_fashion",
    version: "3.0.0",
    name: "FSC Outdoor Courtyard",
    brandId: "BRAND_FSC_001",
    environmentId: "ENV_OUTDOOR_TERRACE_004",
    compositionId: "COMP_EDITORIAL_003",
    defaultStylePackId: "STYLE_LUXURY_EDITORIAL_001",
    defaultBrandingId: "BRAND_BRASS_PLAQUE_002",
    allowedVariantIds: ["VAR_GOLDEN_HOUR_006", "VAR_EDITORIAL_005"],
    mandatoryShotIds: ["SHOT_HERO_001", "SHOT_LOOKBOOK_002"],
    createdBy: "Nuerex Enterprise System",
    approvedBy: "Chief Creative Officer",
    approvalDate: "2026-08-01",
    usageCount: 640,
    performanceScore: 92.5,
    deprecated: false
  },
  christmas_studio: {
    id: "christmas_studio",
    version: "3.0.0",
    name: "FSC Christmas Pavilion",
    brandId: "BRAND_FSC_001",
    environmentId: "ENV_CHRISTMAS_PAVILION_005",
    compositionId: "COMP_HERO_PORTRAIT_001",
    defaultStylePackId: "STYLE_LUXURY_EDITORIAL_001",
    defaultBrandingId: "BRAND_MOUNTED_3D_001",
    allowedVariantIds: ["VAR_FESTIVE_WARMTH_007"],
    mandatoryShotIds: ["SHOT_HERO_001", "SHOT_SIDE_003"],
    createdBy: "Nuerex Enterprise System",
    approvedBy: "Chief Creative Officer",
    approvalDate: "2026-08-01",
    usageCount: 420,
    performanceScore: 96.1,
    deprecated: false
  },
  black_friday_studio: {
    id: "black_friday_studio",
    version: "3.0.0",
    name: "FSC Black Friday Arena",
    brandId: "BRAND_FSC_001",
    environmentId: "ENV_BLACK_FRIDAY_ARENA_006",
    compositionId: "COMP_HERO_PORTRAIT_001",
    defaultStylePackId: "STYLE_NIKE_STREET_003",
    defaultBrandingId: "BRAND_BACKLIT_MAGENTA_003",
    allowedVariantIds: ["VAR_HIGH_ENERGY_008"],
    mandatoryShotIds: ["SHOT_HERO_001", "SHOT_LOOKBOOK_002"],
    createdBy: "Nuerex Enterprise System",
    approvedBy: "Chief Creative Officer",
    approvalDate: "2026-08-01",
    usageCount: 510,
    performanceScore: 95.7,
    deprecated: false
  },
  minimal_product_studio: {
    id: "minimal_product_studio",
    version: "3.0.0",
    name: "FSC Product Lab",
    brandId: "BRAND_FSC_001",
    environmentId: "ENV_PRODUCT_LAB_007",
    compositionId: "COMP_PRODUCT_HERO_002",
    defaultStylePackId: "STYLE_APPLE_MINIMAL_002",
    defaultBrandingId: "BRAND_BRASS_PLAQUE_002",
    allowedVariantIds: ["VAR_MINIMAL_004"],
    mandatoryShotIds: ["SHOT_HERO_001", "SHOT_MACRO_004"],
    createdBy: "Nuerex Enterprise System",
    approvedBy: "Chief Creative Officer",
    approvalDate: "2026-08-01",
    usageCount: 1100,
    performanceScore: 98.2,
    deprecated: false
  }
};
